# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=62)),
                ('street_adress', models.CharField(max_length=95)),
                ('post_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=35)),
                ('country', models.CharField(max_length=70)),
                ('nationality', models.CharField(max_length=70)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
